# ===== Scouter API =====
scouter.api.url=
# optional: "Bearer xxx" 같은 값
scouter.auth.header=
http.timeout.seconds=

# ===== MySQL =====
db.jdbcUrl=http://127.0.0.1:8086
db.username=test
db.password=test
db.poolSize=10

# ===== Object Sync =====
sync.enabled=false
sync.interval.seconds=
inactive.grace.minutes=
batch.size=

# ===== Kafka Consumer =====
dispatch.enabled=false
kafka.bootstrap.servers=http://127.0.0.1:8086
kafka.group.id=
kafka.topic.alert=
kafka.auto.offset.reset=
kafka.enable.auto.commit=
kafka.max.poll.records=
kafka.poll.timeout.ms=

dispatch.workerThreads=

# ===== SMS =====
dispatch.sms.enabled=false

# ===== Logging =====
log.dir=
log.file.prefix=
log.timezone=
log.append=
# 로그 보관 기간(일). 0 이하면 삭제 안 함
log.retention.days=
# 로그 정리 주기(시간). 0~23
log.cleanup.hour=

# ===== EAI =====
sys.SysId=
sys.sURL=

# ===== ETL =====
etl.enabled=true
etl.interval.seconds=60
etl.lookback.minutes=10
etl.query.delay.seconds=15

etl.influx.url=http://127.0.0.1:8086
etl.influx.user=test
etl.influx.pass=test
etl.influx.db=scouter
etl.influx.measurement=counter

etl.tags=obj,objFamily,objType,objHashTag
etl.fields=ActiveService,ApiErrorRate,ApiTPS,ApiTime,ApiTimeByService,CpuTime,Elapsed90%,ElapsedTime,ErrorRate,GcCount,GcTime,HeapTotal,HeapUsed,PermPercent,PermUsed,QueuingTime,RecentUser,ServiceCount,SqlErrorRate,SqlTPS,SqlTime,SqlTimeByService,TPS

# etl.fieldAgg=CpuTime=max,ElapsedTime=max,Elapsed90%=max,GcCount=max,GcTime=max,ActiveService=max,RecentUser=max,ServiceCount=max
etl.fieldAgg=ActiveService=MEAN,ActiveService=MAX,ApiErrorRate=MEAN,ApiErrorRate=MAX,ApiTPS=MEAN,ApiTime=MEAN,ApiTimeByService=MEAN,CpuTime=SUM,Elapsed90%=MEAN,ElapsedTime=MEAN,ErrorRate=MEAN,ErrorRate=MAX,GcCount=SUM,GcCount=MAX,GcTime=SUM,GcTime=MAX,GcTime=PERCENTILE,HeapTotal=MEAN,HeapUsed=MEAN,HeapUsed=MAX,PermPercent=MEAN,PermPercent=MAX,PermUsed=MEAN,PermUsed=MAX,QueuingTime=MEAN,RecentUser=MEAN,RecentUser=MAX,ServiceCount=MEAN,ServiceCount=MAX,SqlErrorRate=MEAN,SqlErrorRate=MAX,SqlTPS=MEAN,SqlTime=MEAN,SqlTimeByService=MEAN,TPS=MEAN

etl.mysql.table=scouter_counter_1m
etl.state.file=./config/etl_state.properties